name: Regenerate Story Assets

on:
  workflow_dispatch: {}
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install packaging google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Clear prompts folder (except example.html)
      run: |
        find prompts -mindepth 1 -not -name 'example.html' -delete
        echo "Prompts folder cleared except example.html."


      - name: Sync prompts from Google Docs
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python tools/sync_prompts.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add prompts
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[bot] Update story assets from Google Docs"
            git push
          fi
